### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by n0toose** [NT-Bourgeois-Iridescence-Technologies/Raven-Client#1]
First off, huge hats off for the thing you are pulling off.

I believe that this would get way more attention, if the README.md file was more detailed as far as descriptions and instructions go. (I'd love to contribute one myself, but I don't presently own a PSP and therefore cannot test this client on physical hardware.) 

I found out about this project through this video and word of mouth; https://youtu.be/dfkqNZxGV4g

**Comment by IridescentRose** [comment]
Thanks for coming here, and this version is yet to really be developed however, so it will be getting updates when reworked-core lands in Stardust.

**Comment by IridescentRose** [comment]
Since it landed, we are getting some changes @AlwaysLivid

**Comment by IridescentRose** [comment]
Will be completed in v0.2 release goals
