### ISSUE TITLE
Crashing after launch on PSPEmu

### ISSUE THREAD

**Issue by koutsie** [NT-Bourgeois-Iridescence-Technologies/Raven-Client#2]
I haven't debugged yet but non-usable on the PSVita via Adrenaline AON

**Comment by IridescentRose** [comment]
Alright, but Stardust has cross platform support to the Vita and @MotoLegacy is working on getting a native port running instead.

**Comment by koutsie** [comment]
oh shi, well then!
i did not know about this, thanks.
